CREATE TABLE IF NOT EXISTS ScheduleI (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    phone BIGINT UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    date DATE,
    time TIME
);